# shellcheck shell=bash
about-alias 'kubectl aliases'

function _set_pkg_aliases() {
	if _command_exists kubectl; then
		alias k='kubectl'
		alias kg='kubectl get'
		alias kd='kubectl describe'
		alias kdel='kubectl delete'
		alias klog='kubectl logs'
		alias keve='kubectl events'
		alias kexe='kubectl exec'
		alias kns='kubectl ns'
		alias kctx='kubectl ctx'
		alias kk='kubectl krew'

		alias kgcr='kubectl get clusterrole'
		alias kgcrb='kubectl get clusterrolebinding'
		alias kgcm='kubectl get configmap'
		alias kgcj='kubectl get cronjob'
		alias kgcrd='kubectl get customresourcedefinition'

		alias kgd='kubectl get deployment'
		alias kgi='kubectl get ingress'
		alias kgic='kubectl get ingressclass'
		alias kgj='kubectl get job'
		alias kgns='kubectl get namespace'
		alias kgpdb='kubectl get poddisruptionbudget'
		alias kgpc='kubectl get priorityclass'
		alias kgq='kubectl get quota'
		alias kgr='kubectl get role'
		alias kgrb='kubectl get rolebinding'
		alias kgse='kubectl get secret'
		alias kgsedr='kubectl get secret docker-registry'
		alias kgseg='kubectl get secret generic'
		alias kgset='kubectl get secret tls'
		alias kgsr='kubectl get service'
		alias kgsrci='kubectl get service clusterip'
		alias kgsren='kubectl get service externalname'
		alias kgsrlb='kubectl get service loadbalancer'
		alias kgsrnp='kubectl get service nodeport'
		alias kgsa='kubectl get serviceaccount'

		alias kgcran='kubectl get clusterrole --all-namespaces'
		alias kgcrban='kubectl get clusterrolebinding --all-namespaces'
		alias kgcman='kubectl get configmap --all-namespaces'
		alias kgcjan='kubectl get cronjob --all-namespaces'
		alias kgcrdan='kubectl get customresourcedefinition --all-namespaces'
		alias kgdan='kubectl get deployment --all-namespaces'
		alias kgian='kubectl get ingress --all-namespaces'
		alias kgican='kubectl get ingressclass --all-namespaces'
		alias kgjan='kubectl get job --all-namespaces'
		alias kgnsan='kubectl get namespace --all-namespaces'
		alias kgpdban='kubectl get poddisruptionbudget --all-namespaces'
		alias kgpcan='kubectl get priorityclass --all-namespaces'
		alias kgqan='kubectl get quota --all-namespaces'
		alias kgran='kubectl get role --all-namespaces'
		alias kgrban='kubectl get rolebinding --all-namespaces'
		alias kgsean='kubectl get secret --all-namespaces'
		alias kgsedran='kubectl get secret docker-registry --all-namespaces'
		alias kgsegan='kubectl get secret generic --all-namespaces'
		alias kgsetan='kubectl get secret tls --all-namespaces'
		alias kgsran='kubectl get service --all-namespaces'
		alias kgsrcian='kubectl get service clusterip --all-namespaces'
		alias kgsrenan='kubectl get service externalname --all-namespaces'
		alias kgsrlban='kubectl get service loadbalancer --all-namespaces'
		alias kgsrnpan='kubectl get service nodeport --all-namespaces'
		alias kgsaan='kubectl get serviceaccount --all-namespaces'

		alias kdcr='kubectl describe clusterrole'
		alias kdcrb='kubectl describe clusterrolebinding'
		alias kdcm='kubectl describe configmap'
		alias kdcj='kubectl describe cronjob'
		alias kdcrd='kubectl describe customresourcedefinition'
		alias kdd='kubectl describe deployment'
		alias kdi='kubectl describe ingress'
		alias kdic='kubectl describe ingressclass'
		alias kdj='kubectl describe job'
		alias kdns='kubectl describe namespace'
		alias kdpdb='kubectl describe poddisruptionbuddescribe'
		alias kdpc='kubectl describe priorityclass'
		alias kdq='kubectl describe quota'
		alias kdr='kubectl describe role'
		alias kdrb='kubectl describe rolebinding'
		alias kdse='kubectl describe secret'
		alias kdsedr='kubectl describe secret docker-registry'
		alias kdseg='kubectl describe secret generic'
		alias kdset='kubectl describe secret tls'
		alias kdsr='kubectl describe service'
		alias kdsrci='kubectl describe service clusterip'
		alias kdsren='kubectl describe service externalname'
		alias kdsrlb='kubectl describe service loadbalancer'
		alias kdsrnp='kubectl describe service nodeport'
		alias kdsa='kubectl describe serviceaccount'

		alias kdlcr='kubectl delete clusterrole'
		alias kdlcrb='kubectl delete clusterrolebinding'
		alias kdlcm='kubectl delete configmap'
		alias kdlcrd='kubectl delete customresourcedefinition'
		alias kdlcj='kubectl delete cronjob'
		alias kdld='kubectl delete deployment'
		alias kdli='kubectl delete ingress'
		alias kdlic='kubectl delete ingressclass'
		alias kdlj='kubectl delete job'
		alias kdlns='kubectl delete namespace'
		alias kdlpdb='kubectl delete poddisruptionbuddelete'
		alias kdlpc='kubectl delete priorityclass'
		alias kdlq='kubectl delete quota'
		alias kdlr='kubectl delete role'
		alias kdlrb='kubectl delete rolebinding'
		alias kdlse='kubectl delete secret'
		alias kdlsedr='kubectl delete secret docker-registry'
		alias kdlseg='kubectl delete secret generic'
		alias kdlset='kubectl delete secret tls'
		alias kdlsr='kubectl delete service'
		alias kdlsrci='kubectl delete service clusterip'
		alias kdlsren='kubectl delete service externalname'
		alias kdlsrlb='kubectl delete service loadbalancer'
		alias kdlsrnp='kubectl delete service nodeport'
		alias kdlsa='kubectl delete serviceaccount'

		alias kdlaa='kubectl delete all --all'
		# launches a disposable netshoot pod in the k8s cluster
		alias knetshoot='kubectl run netshoot-$(date +%s) --rm -i --tty --image nicolaka/netshoot -- /bin/bash'
	fi
}

_set_pkg_aliases
